# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test and Publish WebAPi Container Image

on:
  push:
    branches: [ "main" ]
    tags: [ "v1*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  {} # allow manually trigger workflow

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get Go version from go.mod
      id: get_go_version
      run: echo "go_version=$(grep -m1 'go ' go.mod | awk '{print $2}')" >> $GITHUB_OUTPUT

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ steps.get_go_version.outputs.go_version }}

    - name: Build
      run: go build -v ./cmd/wac-tg-jv-backend

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Docker Metadata action
      id: meta
      uses: docker/metadata-action@v4.6.0
      with:
        images: xgolis/wac-tg-jv-backend
        tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=branch,suffix={{date '.YYYYMMDD.HHmm'}}
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
         username: xgolis
         password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        file: ./build/docker/Dockerfile
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: ${{ steps.meta.outputs.tags }}
